
export const PLAYER_STATE = {
  IDLE:"IDLE",
  WALKING:"WALKING",
  REPELLING: "REPELLING",
  ATTRACTING: "ATTRACTING",
  FALLING:"FALLING",
  JUMPING: "JUMPING"
}

export const ATTACK_STATE = {
  IDLE: "IDLE",
  STRIKE: "STRIKE",
  RELOAD: "RELOAD",
  CHARGE: "CHARGE",
  CHARGE2: "CHARGE2",
  FIRE: "FIRE"
}
